/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrawlerRoomRouteImport } from './routes/crawler-room'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known.oauth-authorization-server'
import { Route as DotwellKnownOauthProtectedResourceRouteImport } from './routes/[.]well-known.oauth-protected-resource'
import { Route as DotwellKnownOpenaiAppsChallengeRouteImport } from './routes/[.]well-known.openai-apps-challenge'
import { Route as OauthConsentRouteImport } from './routes/oauth.consent'
import { Route as OauthRegisterRouteImport } from './routes/oauth.register'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as DotwellKnownOauthProtectedResourceMcpRouteImport } from './routes/[.]well-known.oauth-protected-resource.mcp'
import { Route as ApiPublicDataDeletionRouteImport } from './routes/api.public.data-deletion'
import { Route as ApiPublicHealthRouteImport } from './routes/api.public.health'
import { Route as ApiPublicMcpRouteImport } from './routes/api.public.mcp'
import { Route as ApiPublicSupportRouteImport } from './routes/api.public.support'
import { Route as ApiPublicAdminCleanupRouteImport } from './routes/api.public.admin.cleanup'
import { Route as ApiPublicRoomUploadRouteImport } from './routes/api.public.room.upload'
import { Route as DotwellKnownOauthProtectedResourceApiPublicMcpRouteImport } from './routes/[.]well-known.oauth-protected-resource.api.public.mcp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrawlerRoomRoute = CrawlerRoomRouteImport.update({
  id: '/crawler-room',
  path: '/crawler-room',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthProtectedResourceRoute =
  DotwellKnownOauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOpenaiAppsChallengeRoute =
  DotwellKnownOpenaiAppsChallengeRouteImport.update({
    id: '/.well-known/openai-apps-challenge',
    path: '/.well-known/openai-apps-challenge',
    getParentRoute: () => rootRouteImport,
  } as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthRegisterRoute = OauthRegisterRouteImport.update({
  id: '/oauth/register',
  path: '/oauth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthProtectedResourceMcpRoute =
  DotwellKnownOauthProtectedResourceMcpRouteImport.update({
    id: '/mcp',
    path: '/mcp',
    getParentRoute: () => DotwellKnownOauthProtectedResourceRoute,
  } as any)
const ApiPublicDataDeletionRoute = ApiPublicDataDeletionRouteImport.update({
  id: '/api/public/data-deletion',
  path: '/api/public/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMcpRoute = ApiPublicMcpRouteImport.update({
  id: '/api/public/mcp',
  path: '/api/public/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSupportRoute = ApiPublicSupportRouteImport.update({
  id: '/api/public/support',
  path: '/api/public/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminCleanupRoute = ApiPublicAdminCleanupRouteImport.update({
  id: '/api/public/admin/cleanup',
  path: '/api/public/admin/cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRoomUploadRoute = ApiPublicRoomUploadRouteImport.update({
  id: '/api/public/room/upload',
  path: '/api/public/room/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthProtectedResourceApiPublicMcpRoute =
  DotwellKnownOauthProtectedResourceApiPublicMcpRouteImport.update({
    id: '/api/public/mcp',
    path: '/api/public/mcp',
    getParentRoute: () => DotwellKnownOauthProtectedResourceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crawler-room': typeof CrawlerRoomRoute
  '/data-deletion': typeof DataDeletionRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRouteWithChildren
  '/.well-known/openai-apps-challenge': typeof DotwellKnownOpenaiAppsChallengeRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/register': typeof OauthRegisterRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.well-known/oauth-protected-resource/mcp': typeof DotwellKnownOauthProtectedResourceMcpRoute
  '/api/public/data-deletion': typeof ApiPublicDataDeletionRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/support': typeof ApiPublicSupportRoute
  '/api/public/admin/cleanup': typeof ApiPublicAdminCleanupRoute
  '/api/public/room/upload': typeof ApiPublicRoomUploadRoute
  '/.well-known/oauth-protected-resource/api/public/mcp': typeof DotwellKnownOauthProtectedResourceApiPublicMcpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crawler-room': typeof CrawlerRoomRoute
  '/data-deletion': typeof DataDeletionRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRouteWithChildren
  '/.well-known/openai-apps-challenge': typeof DotwellKnownOpenaiAppsChallengeRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/register': typeof OauthRegisterRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.well-known/oauth-protected-resource/mcp': typeof DotwellKnownOauthProtectedResourceMcpRoute
  '/api/public/data-deletion': typeof ApiPublicDataDeletionRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/support': typeof ApiPublicSupportRoute
  '/api/public/admin/cleanup': typeof ApiPublicAdminCleanupRoute
  '/api/public/room/upload': typeof ApiPublicRoomUploadRoute
  '/.well-known/oauth-protected-resource/api/public/mcp': typeof DotwellKnownOauthProtectedResourceApiPublicMcpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crawler-room': typeof CrawlerRoomRoute
  '/data-deletion': typeof DataDeletionRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRouteWithChildren
  '/.well-known/openai-apps-challenge': typeof DotwellKnownOpenaiAppsChallengeRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/register': typeof OauthRegisterRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.well-known/oauth-protected-resource/mcp': typeof DotwellKnownOauthProtectedResourceMcpRoute
  '/api/public/data-deletion': typeof ApiPublicDataDeletionRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/support': typeof ApiPublicSupportRoute
  '/api/public/admin/cleanup': typeof ApiPublicAdminCleanupRoute
  '/api/public/room/upload': typeof ApiPublicRoomUploadRoute
  '/.well-known/oauth-protected-resource/api/public/mcp': typeof DotwellKnownOauthProtectedResourceApiPublicMcpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crawler-room'
    | '/data-deletion'
    | '/mcp'
    | '/privacy'
    | '/safety'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/.well-known/openai-apps-challenge'
    | '/oauth/consent'
    | '/oauth/register'
    | '/.lovable/oauth/consent'
    | '/.well-known/oauth-protected-resource/mcp'
    | '/api/public/data-deletion'
    | '/api/public/health'
    | '/api/public/mcp'
    | '/api/public/support'
    | '/api/public/admin/cleanup'
    | '/api/public/room/upload'
    | '/.well-known/oauth-protected-resource/api/public/mcp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crawler-room'
    | '/data-deletion'
    | '/mcp'
    | '/privacy'
    | '/safety'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/.well-known/openai-apps-challenge'
    | '/oauth/consent'
    | '/oauth/register'
    | '/.lovable/oauth/consent'
    | '/.well-known/oauth-protected-resource/mcp'
    | '/api/public/data-deletion'
    | '/api/public/health'
    | '/api/public/mcp'
    | '/api/public/support'
    | '/api/public/admin/cleanup'
    | '/api/public/room/upload'
    | '/.well-known/oauth-protected-resource/api/public/mcp'
  id:
    | '__root__'
    | '/'
    | '/crawler-room'
    | '/data-deletion'
    | '/mcp'
    | '/privacy'
    | '/safety'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/.well-known/openai-apps-challenge'
    | '/oauth/consent'
    | '/oauth/register'
    | '/.lovable/oauth/consent'
    | '/.well-known/oauth-protected-resource/mcp'
    | '/api/public/data-deletion'
    | '/api/public/health'
    | '/api/public/mcp'
    | '/api/public/support'
    | '/api/public/admin/cleanup'
    | '/api/public/room/upload'
    | '/.well-known/oauth-protected-resource/api/public/mcp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrawlerRoomRoute: typeof CrawlerRoomRoute
  DataDeletionRoute: typeof DataDeletionRoute
  McpRoute: typeof McpRoute
  PrivacyRoute: typeof PrivacyRoute
  SafetyRoute: typeof SafetyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  DotwellKnownOauthProtectedResourceRoute: typeof DotwellKnownOauthProtectedResourceRouteWithChildren
  DotwellKnownOpenaiAppsChallengeRoute: typeof DotwellKnownOpenaiAppsChallengeRoute
  OauthConsentRoute: typeof OauthConsentRoute
  OauthRegisterRoute: typeof OauthRegisterRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicDataDeletionRoute: typeof ApiPublicDataDeletionRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicMcpRoute: typeof ApiPublicMcpRoute
  ApiPublicSupportRoute: typeof ApiPublicSupportRoute
  ApiPublicAdminCleanupRoute: typeof ApiPublicAdminCleanupRoute
  ApiPublicRoomUploadRoute: typeof ApiPublicRoomUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crawler-room': {
      id: '/crawler-room'
      path: '/crawler-room'
      fullPath: '/crawler-room'
      preLoaderRoute: typeof CrawlerRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/openai-apps-challenge': {
      id: '/.well-known/openai-apps-challenge'
      path: '/.well-known/openai-apps-challenge'
      fullPath: '/.well-known/openai-apps-challenge'
      preLoaderRoute: typeof DotwellKnownOpenaiAppsChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/register': {
      id: '/oauth/register'
      path: '/oauth/register'
      fullPath: '/oauth/register'
      preLoaderRoute: typeof OauthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource/mcp': {
      id: '/.well-known/oauth-protected-resource/mcp'
      path: '/mcp'
      fullPath: '/.well-known/oauth-protected-resource/mcp'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceMcpRouteImport
      parentRoute: typeof DotwellKnownOauthProtectedResourceRoute
    }
    '/api/public/data-deletion': {
      id: '/api/public/data-deletion'
      path: '/api/public/data-deletion'
      fullPath: '/api/public/data-deletion'
      preLoaderRoute: typeof ApiPublicDataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mcp': {
      id: '/api/public/mcp'
      path: '/api/public/mcp'
      fullPath: '/api/public/mcp'
      preLoaderRoute: typeof ApiPublicMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/support': {
      id: '/api/public/support'
      path: '/api/public/support'
      fullPath: '/api/public/support'
      preLoaderRoute: typeof ApiPublicSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/cleanup': {
      id: '/api/public/admin/cleanup'
      path: '/api/public/admin/cleanup'
      fullPath: '/api/public/admin/cleanup'
      preLoaderRoute: typeof ApiPublicAdminCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/room/upload': {
      id: '/api/public/room/upload'
      path: '/api/public/room/upload'
      fullPath: '/api/public/room/upload'
      preLoaderRoute: typeof ApiPublicRoomUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource/api/public/mcp': {
      id: '/.well-known/oauth-protected-resource/api/public/mcp'
      path: '/api/public/mcp'
      fullPath: '/.well-known/oauth-protected-resource/api/public/mcp'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceApiPublicMcpRouteImport
      parentRoute: typeof DotwellKnownOauthProtectedResourceRoute
    }
  }
}

interface DotwellKnownOauthProtectedResourceRouteChildren {
  DotwellKnownOauthProtectedResourceMcpRoute: typeof DotwellKnownOauthProtectedResourceMcpRoute
  DotwellKnownOauthProtectedResourceApiPublicMcpRoute: typeof DotwellKnownOauthProtectedResourceApiPublicMcpRoute
}

const DotwellKnownOauthProtectedResourceRouteChildren: DotwellKnownOauthProtectedResourceRouteChildren =
  {
    DotwellKnownOauthProtectedResourceMcpRoute:
      DotwellKnownOauthProtectedResourceMcpRoute,
    DotwellKnownOauthProtectedResourceApiPublicMcpRoute:
      DotwellKnownOauthProtectedResourceApiPublicMcpRoute,
  }

const DotwellKnownOauthProtectedResourceRouteWithChildren =
  DotwellKnownOauthProtectedResourceRoute._addFileChildren(
    DotwellKnownOauthProtectedResourceRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrawlerRoomRoute: CrawlerRoomRoute,
  DataDeletionRoute: DataDeletionRoute,
  McpRoute: McpRoute,
  PrivacyRoute: PrivacyRoute,
  SafetyRoute: SafetyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  DotwellKnownOauthProtectedResourceRoute:
    DotwellKnownOauthProtectedResourceRouteWithChildren,
  DotwellKnownOpenaiAppsChallengeRoute: DotwellKnownOpenaiAppsChallengeRoute,
  OauthConsentRoute: OauthConsentRoute,
  OauthRegisterRoute: OauthRegisterRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicDataDeletionRoute: ApiPublicDataDeletionRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicMcpRoute: ApiPublicMcpRoute,
  ApiPublicSupportRoute: ApiPublicSupportRoute,
  ApiPublicAdminCleanupRoute: ApiPublicAdminCleanupRoute,
  ApiPublicRoomUploadRoute: ApiPublicRoomUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
