/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrawlerRoomRouteImport } from './routes/crawler-room'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as InstallRouteImport } from './routes/install'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as DotwellKnownOpenaiAppsChallengeRouteImport } from './routes/[.]well-known.openai-apps-challenge'
import { Route as ApiPublicDataDeletionRouteImport } from './routes/api.public.data-deletion'
import { Route as ApiPublicHealthRouteImport } from './routes/api.public.health'
import { Route as ApiPublicMcpRouteImport } from './routes/api.public.mcp'
import { Route as ApiPublicSupportRouteImport } from './routes/api.public.support'
import { Route as ApiPublicAdminCleanupRouteImport } from './routes/api.public.admin.cleanup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrawlerRoomRoute = CrawlerRoomRouteImport.update({
  id: '/crawler-room',
  path: '/crawler-room',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOpenaiAppsChallengeRoute =
  DotwellKnownOpenaiAppsChallengeRouteImport.update({
    id: '/.well-known/openai-apps-challenge',
    path: '/.well-known/openai-apps-challenge',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDataDeletionRoute = ApiPublicDataDeletionRouteImport.update({
  id: '/api/public/data-deletion',
  path: '/api/public/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMcpRoute = ApiPublicMcpRouteImport.update({
  id: '/api/public/mcp',
  path: '/api/public/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSupportRoute = ApiPublicSupportRouteImport.update({
  id: '/api/public/support',
  path: '/api/public/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminCleanupRoute = ApiPublicAdminCleanupRouteImport.update({
  id: '/api/public/admin/cleanup',
  path: '/api/public/admin/cleanup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crawler-room': typeof CrawlerRoomRoute
  '/data-deletion': typeof DataDeletionRoute
  '/install': typeof InstallRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/.well-known/openai-apps-challenge': typeof DotwellKnownOpenaiAppsChallengeRoute
  '/api/public/data-deletion': typeof ApiPublicDataDeletionRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/support': typeof ApiPublicSupportRoute
  '/api/public/admin/cleanup': typeof ApiPublicAdminCleanupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crawler-room': typeof CrawlerRoomRoute
  '/data-deletion': typeof DataDeletionRoute
  '/install': typeof InstallRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/.well-known/openai-apps-challenge': typeof DotwellKnownOpenaiAppsChallengeRoute
  '/api/public/data-deletion': typeof ApiPublicDataDeletionRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/support': typeof ApiPublicSupportRoute
  '/api/public/admin/cleanup': typeof ApiPublicAdminCleanupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crawler-room': typeof CrawlerRoomRoute
  '/data-deletion': typeof DataDeletionRoute
  '/install': typeof InstallRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/.well-known/openai-apps-challenge': typeof DotwellKnownOpenaiAppsChallengeRoute
  '/api/public/data-deletion': typeof ApiPublicDataDeletionRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/support': typeof ApiPublicSupportRoute
  '/api/public/admin/cleanup': typeof ApiPublicAdminCleanupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crawler-room'
    | '/data-deletion'
    | '/install'
    | '/mcp'
    | '/privacy'
    | '/safety'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/.well-known/openai-apps-challenge'
    | '/api/public/data-deletion'
    | '/api/public/health'
    | '/api/public/mcp'
    | '/api/public/support'
    | '/api/public/admin/cleanup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crawler-room'
    | '/data-deletion'
    | '/install'
    | '/mcp'
    | '/privacy'
    | '/safety'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/.well-known/openai-apps-challenge'
    | '/api/public/data-deletion'
    | '/api/public/health'
    | '/api/public/mcp'
    | '/api/public/support'
    | '/api/public/admin/cleanup'
  id:
    | '__root__'
    | '/'
    | '/crawler-room'
    | '/data-deletion'
    | '/install'
    | '/mcp'
    | '/privacy'
    | '/safety'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/.well-known/openai-apps-challenge'
    | '/api/public/data-deletion'
    | '/api/public/health'
    | '/api/public/mcp'
    | '/api/public/support'
    | '/api/public/admin/cleanup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrawlerRoomRoute: typeof CrawlerRoomRoute
  DataDeletionRoute: typeof DataDeletionRoute
  InstallRoute: typeof InstallRoute
  McpRoute: typeof McpRoute
  PrivacyRoute: typeof PrivacyRoute
  SafetyRoute: typeof SafetyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  DotwellKnownOpenaiAppsChallengeRoute: typeof DotwellKnownOpenaiAppsChallengeRoute
  ApiPublicDataDeletionRoute: typeof ApiPublicDataDeletionRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicMcpRoute: typeof ApiPublicMcpRoute
  ApiPublicSupportRoute: typeof ApiPublicSupportRoute
  ApiPublicAdminCleanupRoute: typeof ApiPublicAdminCleanupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crawler-room': {
      id: '/crawler-room'
      path: '/crawler-room'
      fullPath: '/crawler-room'
      preLoaderRoute: typeof CrawlerRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/openai-apps-challenge': {
      id: '/.well-known/openai-apps-challenge'
      path: '/.well-known/openai-apps-challenge'
      fullPath: '/.well-known/openai-apps-challenge'
      preLoaderRoute: typeof DotwellKnownOpenaiAppsChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/data-deletion': {
      id: '/api/public/data-deletion'
      path: '/api/public/data-deletion'
      fullPath: '/api/public/data-deletion'
      preLoaderRoute: typeof ApiPublicDataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mcp': {
      id: '/api/public/mcp'
      path: '/api/public/mcp'
      fullPath: '/api/public/mcp'
      preLoaderRoute: typeof ApiPublicMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/support': {
      id: '/api/public/support'
      path: '/api/public/support'
      fullPath: '/api/public/support'
      preLoaderRoute: typeof ApiPublicSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/cleanup': {
      id: '/api/public/admin/cleanup'
      path: '/api/public/admin/cleanup'
      fullPath: '/api/public/admin/cleanup'
      preLoaderRoute: typeof ApiPublicAdminCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrawlerRoomRoute: CrawlerRoomRoute,
  DataDeletionRoute: DataDeletionRoute,
  InstallRoute: InstallRoute,
  McpRoute: McpRoute,
  PrivacyRoute: PrivacyRoute,
  SafetyRoute: SafetyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  DotwellKnownOpenaiAppsChallengeRoute: DotwellKnownOpenaiAppsChallengeRoute,
  ApiPublicDataDeletionRoute: ApiPublicDataDeletionRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicMcpRoute: ApiPublicMcpRoute,
  ApiPublicSupportRoute: ApiPublicSupportRoute,
  ApiPublicAdminCleanupRoute: ApiPublicAdminCleanupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
