/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DotwellKnownOauthProtectedResourceRouteImport } from './routes/[.]well-known.oauth-protected-resource'
import { Route as OauthConsentRouteImport } from './routes/oauth.consent'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicDataDeletionRouteImport } from './routes/api.public.data-deletion'
import { Route as ApiPublicHealthRouteImport } from './routes/api.public.health'
import { Route as ApiPublicMcpRouteImport } from './routes/api.public.mcp'
import { Route as ApiPublicSupportRouteImport } from './routes/api.public.support'
import { Route as ApiPublicAdminCleanupRouteImport } from './routes/api.public.admin.cleanup'
import { Route as ApiPublicRoomUploadRouteImport } from './routes/api.public.room.upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthProtectedResourceRoute =
  DotwellKnownOauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDataDeletionRoute = ApiPublicDataDeletionRouteImport.update({
  id: '/api/public/data-deletion',
  path: '/api/public/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMcpRoute = ApiPublicMcpRouteImport.update({
  id: '/api/public/mcp',
  path: '/api/public/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSupportRoute = ApiPublicSupportRouteImport.update({
  id: '/api/public/support',
  path: '/api/public/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminCleanupRoute = ApiPublicAdminCleanupRouteImport.update({
  id: '/api/public/admin/cleanup',
  path: '/api/public/admin/cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRoomUploadRoute = ApiPublicRoomUploadRouteImport.update({
  id: '/api/public/room/upload',
  path: '/api/public/room/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/data-deletion': typeof ApiPublicDataDeletionRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/support': typeof ApiPublicSupportRoute
  '/api/public/admin/cleanup': typeof ApiPublicAdminCleanupRoute
  '/api/public/room/upload': typeof ApiPublicRoomUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/data-deletion': typeof ApiPublicDataDeletionRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/support': typeof ApiPublicSupportRoute
  '/api/public/admin/cleanup': typeof ApiPublicAdminCleanupRoute
  '/api/public/room/upload': typeof ApiPublicRoomUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/data-deletion': typeof ApiPublicDataDeletionRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/support': typeof ApiPublicSupportRoute
  '/api/public/admin/cleanup': typeof ApiPublicAdminCleanupRoute
  '/api/public/room/upload': typeof ApiPublicRoomUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/.well-known/oauth-protected-resource'
    | '/oauth/consent'
    | '/.lovable/oauth/consent'
    | '/api/public/data-deletion'
    | '/api/public/health'
    | '/api/public/mcp'
    | '/api/public/support'
    | '/api/public/admin/cleanup'
    | '/api/public/room/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/.well-known/oauth-protected-resource'
    | '/oauth/consent'
    | '/.lovable/oauth/consent'
    | '/api/public/data-deletion'
    | '/api/public/health'
    | '/api/public/mcp'
    | '/api/public/support'
    | '/api/public/admin/cleanup'
    | '/api/public/room/upload'
  id:
    | '__root__'
    | '/'
    | '/.well-known/oauth-protected-resource'
    | '/oauth/consent'
    | '/.lovable/oauth/consent'
    | '/api/public/data-deletion'
    | '/api/public/health'
    | '/api/public/mcp'
    | '/api/public/support'
    | '/api/public/admin/cleanup'
    | '/api/public/room/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DotwellKnownOauthProtectedResourceRoute: typeof DotwellKnownOauthProtectedResourceRoute
  OauthConsentRoute: typeof OauthConsentRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicDataDeletionRoute: typeof ApiPublicDataDeletionRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicMcpRoute: typeof ApiPublicMcpRoute
  ApiPublicSupportRoute: typeof ApiPublicSupportRoute
  ApiPublicAdminCleanupRoute: typeof ApiPublicAdminCleanupRoute
  ApiPublicRoomUploadRoute: typeof ApiPublicRoomUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/data-deletion': {
      id: '/api/public/data-deletion'
      path: '/api/public/data-deletion'
      fullPath: '/api/public/data-deletion'
      preLoaderRoute: typeof ApiPublicDataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mcp': {
      id: '/api/public/mcp'
      path: '/api/public/mcp'
      fullPath: '/api/public/mcp'
      preLoaderRoute: typeof ApiPublicMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/support': {
      id: '/api/public/support'
      path: '/api/public/support'
      fullPath: '/api/public/support'
      preLoaderRoute: typeof ApiPublicSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/cleanup': {
      id: '/api/public/admin/cleanup'
      path: '/api/public/admin/cleanup'
      fullPath: '/api/public/admin/cleanup'
      preLoaderRoute: typeof ApiPublicAdminCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/room/upload': {
      id: '/api/public/room/upload'
      path: '/api/public/room/upload'
      fullPath: '/api/public/room/upload'
      preLoaderRoute: typeof ApiPublicRoomUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DotwellKnownOauthProtectedResourceRoute:
    DotwellKnownOauthProtectedResourceRoute,
  OauthConsentRoute: OauthConsentRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicDataDeletionRoute: ApiPublicDataDeletionRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicMcpRoute: ApiPublicMcpRoute,
  ApiPublicSupportRoute: ApiPublicSupportRoute,
  ApiPublicAdminCleanupRoute: ApiPublicAdminCleanupRoute,
  ApiPublicRoomUploadRoute: ApiPublicRoomUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
